### ISSUE TITLE
Data not showing up again

### ISSUE THREAD

**Issue by ScriptedRain** [ScriptedRain/React-chat-app#4]
![image](https://user-images.githubusercontent.com/71009876/115950950-85123980-a521-11eb-9e86-a8947ef5b777.png)

@krishp058 the app broke again in channel.jsx try do what u did I have added the feature of it sending data to the database but it cant get them.

**Comment by krishp058** [comment]
The data is storing in the database whenever I type in something but we can't view it on the app.

**Comment by krishp058** [comment]
@ScriptedRain 

Could this issue be raised from the commit you did on App.js just then (commit `b7a498d`)?

**Comment by krishp058** [comment]
Fixed by deleting an accidently indentation.
